#define BONUS_UNDO_SERVICE

#define MAX_CHAR_LEN 2048

#define UI_MAX_TOKENS_ARRAY_LENGTH 8
#define UI_MAX_USER_INPUT_LENGTH 2048

#define UI_ARCHIVE_CATALOGUE_NUMBER_INDEX_IN_INPUT_TOKENS 1
#define UI_STATE_OF_DETERIORATION_INDEX_IN_INPUT_TOKENS 2
#define UI_FILE_TYPE_INDEX_IN_INPUT_TOKENS 3
#define UI_YEAR_OF_CREATION_INDEX_IN_INPUT_TOKENS 4
#define UI_FILE_TYPE_INDEX_IN_INPUT_TOKENS_FOR_FILTER 1
#define UI_YEAR_OF_CREATION_INDEX_IN_INPUT_TOKENS_FOR_FILTER 1
#define UI_COMMAND_TYPE_INDEX_IN_INPUT_TOKENS 0